var bingoList = {
    "info": {
        "version": "v8.5"
    },
    "1":[
        {
            "jp":"ビン(妖精)",
            "types":{
                "bottle":1
            },
            "child":"yes",
            "name":"Bottled Fairy"
        },
        {
            "jp":"デクのタネ袋(50)",
            "types":{
                "bulletbag":1
            },
            "child":"yes",
            "name":"Bullet Bag (50)"
        },
        {
            "jp":"ボム袋(30)",
            "types":{
                "bombbag":1
            },
            "child":"yes",
            "name":"Bomb Bag (30)"
        },
        {
            "jp":"まことのメガネ\u001a",
            "types":{
                "botw":1
            },
            "child":"yes",
            "name":"Lens of Truth"
        },
        {
            "jp":"スタルキッド撃破",
            "types":{
                "skullkid":1
            },
            "child":"yes",
            "name":"Defeat a Skull Kid"
        },
        {
            "jp":"デクの実30個以上",
            "types":{
                "nuts":1
            },
            "child":"yes",
            "name":"At least 30 Deku Nuts"
        }
    ],
    "2":[
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"ドドンゴの洞窟のマップとコンパス",
            "types":{
                "dc":1
            },
            "child":"yes",
            "name":"Map & Compass in Dodongo's Cavern"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"デクの樹様の中のマップとコンパス",
            "types":{
                "deku":1
            },
            "child":"yes",
            "name":"Map & Compass in Deku Tree"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"井戸の底のマップとコンパス",
            "types":{
                "botw":1
            },
            "child":"yes",
            "name":"Map & Compass in Bottom of the Well"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"巨人のナイフ",
            "types":{
                "swords":1
            },
            "child":"no",
            "name":"Giant's Knife"
        },
        {
            "subtypes":{
                "songs":1
            },
            "jp":"森のメヌエット",
            "types":{
                "forest":1
            },
            "child":"no",
            "name":"Minuet of Forest"
        },
        {
            "jp":"ゴロンの服",
            "types":{
                "fire":1,
                "dmc":1,
                "tunics":1
            },
            "child":"no",
            "name":"Goron Tunic"
        },
        {
            "jp":"ゾーラの服\u001a",
            "types":{
                "ice":1,
                "tunics":1
            },
            "child":"no",
            "name":"Zora Tunic"
        }
    ],
    "3":[
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"デスマウンテン火口のハートのかけら２つ\u001a",
            "types":{
                "fire":1,
                "dmc":1
            },
            "child":"yes",
            "name":"Both heart pieces in Death Mountain Crater"
        },
        {
            "jp":"妖精のパチンコ",
            "types":{
                "deku":1,
                "bulletbag":1
            },
            "child":"yes",
            "name":"Fairy Slingshot"
        },
        {
            "jp":"歌3つ以上",
            "types":{
                "zl":1,
                "songs":1
            },
            "child":"yes",
            "name":"At least 3 songs"
        },
        {
            "jp":"矢立て(40)",
            "types":{
                "quiver":1,
                "forest":1,
                "atrade":1
            },
            "child":"no",
            "name":"Quiver (40)"
        },
        {
            "jp":"ドドンゴの洞窟のリザルフォス全て撃破",
            "types":{
                "dc":1
            },
            "child":"yes",
            "name":"Defeat all Lizalfos in Dodongo's Cavern"
        },
        {
            "subtypes":{
                "songs":1
            },
            "jp":"炎のボレロ",
            "types":{
                "fire":1,
                "dmc":1
            },
            "child":"no",
            "name":"Bolero of Fire"
        }
    ],
    "4":[
        {
            "jp":"デクの棒30本",
            "types":{
                "atrade":1
            },
            "child":"yes",
            "name":"30 Deku Sticks"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"キングドドンゴ撃破",
            "types":{
                "kd":1,
                "dc":1
            },
            "child":"yes",
            "name":"Defeat King Dodongo"
        },
        {
            "subtypes":{
                "bosskey":1
            },
            "jp":"炎の神殿のボス部屋のカギ",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Fire Temple Boss Key"
        },
        {
            "jp":"ルトの手紙\u001a",
            "types":{
                "bottle":1
            },
            "child":"yes",
            "name":"Ruto's Letter"
        },
        {
            "subtypes":{
                "kd":1
            },
            "jp":"氷の矢",
            "types":{
                "fortress":1,
                "quiver":1
            },
            "child":"yes",
            "name":"Ice Arrows"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"闇の神殿のマップとコンパス",
            "types":{
                "shadow":1
            },
            "child":"yes",
            "name":"Map & Compass in Shadow Temple"
        }
    ],
    "5":[
        {
            "jp":"ゲルドの修練場の未使用のカギ3つ",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"3 unused keys in Gerudo Training Grounds"
        },
        {
            "jp":"デクのタネ袋(40)",
            "types":{
                "deku":1,
                "bulletbag":1
            },
            "child":"yes",
            "name":"Bullet Bag (40)"
        },
        {
            "jp":"青い炎",
            "types":{
                "ganon":1,
                "ice":1,
                "bottle":1
            },
            "child":"yes",
            "name":"Blue Fire"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"ゴーマ撃破",
            "types":{
                "ganon":1,
                "deku":1
            },
            "child":"yes",
            "name":"Defeat Queen Gohma"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"コキリの森エリアの黄金のスタルチュラ３匹",
            "types":{
                "forest":1
            },
            "child":"no",
            "name":"All 3 Kokiri Forest area Skulltulas"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "hearts":1
            },
            "jp":"氷の洞窟のハートのかけら",
            "types":{
                "ice":1
            },
            "child":"yes",
            "name":"Ice Cavern Heart Piece"
        },
        {
            "jp":"服3種類\u001a",
            "types":{
                "fire":1,
                "ice":1,
                "tunics":1
            },
            "child":"no",
            "name":"3 Tunics"
        },
        {
            "subtypes":{
                "bosskey":1
            },
            "jp":"水の神殿のボス部屋のカギ",
            "types":{
                "fortress":1,
                "water":1
            },
            "child":"no",
            "name":"Water Temple Boss Key"
        }
    ],
    "6":[
        {
            "jp":"ゲルドの修練場の未使用のカギ4つ",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"4 unused keys in Gerudo Training Grounds"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"氷の洞窟のマップとコンパス",
            "types":{
                "ice":1
            },
            "child":"yes",
            "name":"Map & Compass in Ice Cavern"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"ホワイトウルフォス撃破",
            "types":{
                "fortress":1,
                "ice":1
            },
            "child":"yes",
            "name":"Defeat a White Wolfos"
        },
        {
            "subtypes":{
                "bosskey":1
            },
            "jp":"ガノン城のボス部屋のカギ",
            "types":{
                "ganon":1,
                "deku":1
            },
            "child":"yes",
            "name":"Ganon's Castle Boss Key"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"井戸の底の黄金のスタルチュラ3匹",
            "types":{
                "botw":1
            },
            "child":"yes",
            "name":"All 3 Skulltulas in Bottom of the Well"
        },
        {
            "jp":"牛(リンクの家)",
            "types":{
                "cow":1
            },
            "child":"no",
            "name":"Cow in House"
        },
        {
            "jp":"デクの樹様の中クリア",
            "types":{
                "ganon":1,
                "deku":1
            },
            "child":"yes",
            "name":"Beat the Deku Tree"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "wallet":1
            },
            "jp":"氷の洞窟の黄金のスタルチュラ3匹",
            "types":{
                "ice":1
            },
            "child":"yes",
            "name":"All 3 Skulltulas in Ice Cavern"
        }
    ],
    "7":[
        {
            "jp":"ドドンゴの洞窟クリア",
            "types":{
                "fortress":1,
                "kd":1,
                "dc":1
            },
            "child":"yes",
            "name":"Beat Dodongo's Cavern"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"ゲルドの砦の黄金のスタルチュラ2匹",
            "types":{
                "fortress":1
            },
            "child":"no",
            "name":"Both Gerudo's Fortress area Skulltulas"
        },
        {
            "jp":"ロンロン牛乳",
            "types":{
                "lonlon":1,
                "bottle":1
            },
            "child":"yes",
            "name":"Milk"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"迷いの森エリアの黄金のスタルチュラ4匹",
            "types":{
                "forest":1
            },
            "child":"no",
            "name":"All 4 Lost Woods area Skulltulas"
        },
        {
            "jp":"4つの空きビンスロットを全て埋める\u001a",
            "types":{
                "bottle":1
            },
            "child":"yes",
            "name":"Fill all 4 Bottle Slots"
        },
        {
            "jp":"青いクスリ",
            "types":{
                "zl":1,
                "atrade":1
            },
            "child":"no",
            "name":"Blue Potion"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"歌4つ以上\u001a",
            "types":{
                "zl":1,
                "songs":1,
                "atrade":1
            },
            "child":"yes",
            "name":"At least 4 songs"
        }
    ],
    "8":[
        {
            "jp":"巨人のサイフ",
            "types":{
                "wallet":1
            },
            "child":"yes",
            "name":"Giant's Wallet"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"デスマウンテン火口の土にマメを植える",
            "types":{
                "beans":1,
                "dmc":1
            },
            "child":"yes",
            "name":"Plant bean in Death Mountain Crater"
        },
        {
            "subtypes":{
                "songs":1
            },
            "jp":"エポナの歌",
            "types":{
                "lonlon":1
            },
            "child":"yes",
            "name":"Epona's Song"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"ヘビーブーツ\u001a",
            "types":{
                "ice":1,
                "boots":1
            },
            "child":"yes",
            "name":"Iron Boots"
        },
        {
            "jp":"ゲルドの修練場の未使用のカギ5つ",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"5 unused keys in Gerudo Training Grounds"
        },
        {
            "jp":"ハート6つ",
            "types":{
                "hearts":1
            },
            "child":"yes",
            "name":"6 Hearts"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"ファントムガノン撃破",
            "types":{
                "pg":1,
                "forest":1
            },
            "child":"yes",
            "name":"Defeat Phantom Ganon"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"水の神殿のマップとコンパス",
            "types":{
                "water":1
            },
            "child":"yes",
            "name":"Map & Compass in Water Temple"
        }
    ],
    "9":[
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"剣3種類と服3種類\u001a",
            "types":{
                "fire":1,
                "swords":1,
                "ice":1,
                "tunics":1
            },
            "child":"no",
            "name":"3 Swords & 3 Tunics"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"靴3種類\u001a",
            "types":{
                "ice":1,
                "boots":1
            },
            "child":"yes",
            "name":"3 Boots"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"ドドンゴの洞窟の黄金のスタルチュラ5匹",
            "types":{
                "dc":1
            },
            "child":"yes",
            "name":"All 5 Skulltulas in Dodongo's Cavern"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"モーファ撃破",
            "types":{
                "water":1
            },
            "child":"yes",
            "name":"Defeat Morpha"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"森の神殿クリア",
            "types":{
                "pg":1,
                "forest":1
            },
            "child":"yes",
            "name":"Beat the Forest Temple"
        }
    ],
    "10":[
        {
            "jp":"500ルピー",
            "types":{
                "wallet":1
            },
            "child":"yes",
            "name":"500 Rupees"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"デクの樹様の中の黄金のスタルチュラ4匹",
            "types":{
                "deku":1
            },
            "child":"yes",
            "name":"All 4 Skulltulas in Deku Tree"
        },
        {
            "subtypes":{
                "child2":1,
                "wallet":1
            },
            "jp":"魔法のマメ7つ以上\u001a",
            "types":{
                "beans":1
            },
            "child":"yes",
            "name":"At least 7 Magic Beans"
        },
        {
            "jp":"大オクタ撃破",
            "types":{
                "jabu":1,
                "ice":1
            },
            "child":"yes",
            "name":"Defeat Big Octo"
        },
        {
            "subtypes":{
                "hearts":1,
                "kd":1
            },
            "jp":"37番目のハートのかけら(子供のゲルドの砦)",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"37th heart piece (Child Fortress)"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"水の神殿クリア",
            "types":{
                "water":1
            },
            "child":"yes",
            "name":"Beat the Water Temple"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"森のメダル",
            "types":{
                "zl":1,
                "pg":1,
                "atrade":1,
                "lightarrow":1,
                "forest":1
            },
            "child":"yes",
            "name":"Forest Medallion"
        },
        {
            "jp":"ゲルドの修練場の未使用のカギ6つ",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"6 unused keys in Gerudo Training Grounds"
        },
        {
            "subtypes":{
                "songs":1
            },
            "jp":"魂のレクイエム",
            "types":{
                "spirit":1
            },
            "child":"yes",
            "name":"Requiem of Spirit"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"歌6つ以上\u001a",
            "types":{
                "zl":1,
                "songs":1,
                "atrade":1
            },
            "child":"no",
            "name":"At least 6 songs"
        }
    ],
    "11":[
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"ロンロン牧場エリアの黄金のスタルチュラ4匹",
            "types":{
                "lonlon":1,
                "jabu":1
            },
            "child":"yes",
            "name":"All 4 Lon-Lon Ranch area Skulltulas"
        },
        {
            "subtypes":{
                "hearts":1,
                "bosskey":1
            },
            "jp":"ボンゴボンゴ撃破",
            "types":{
                "shadow":1
            },
            "child":"yes",
            "name":"Defeat Bongo-Bongo"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"闇の神殿の黄金のスタルチュラ4匹以上",
            "types":{
                "shadow":1
            },
            "child":"no",
            "name":"At least 4 Skulltulas in Shadow Temple"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"カカリコ村エリアの黄金のスタルチュラ8匹",
            "types":{
                "botw":1
            },
            "child":"no",
            "name":"All 8 Kakariko area Skulltulas"
        },
        {
            "jp":"ミラーシールド\u001a",
            "types":{
                "spirit":1,
                "shields":1
            },
            "child":"yes",
            "name":"Mirror Shield"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"森の神殿の黄金のスタルチュラ5匹",
            "types":{
                "forest":1
            },
            "child":"no",
            "name":"All 5 Skulltulas in Forest Temple"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"水のメダル",
            "types":{
                "zl":1,
                "lightarrow":1,
                "water":1,
                "atrade":1
            },
            "child":"yes",
            "name":"Water Medallion"
        },
        {
            "jp":"ゲルドの会員証",
            "types":{
                "fortress":1
            },
            "child":"yes",
            "name":"Gerudo's Card"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"エイミー撃破(緑のポウ)ｴ",
            "types":{
                "fortress":1,
                "quiver":1,
                "forest":1
            },
            "child":"no",
            "name":"Defeat Amy (Green Poe)"
        }
    ],
    "12":[
        {
            "subtypes":{
                "hearts":1,
                "bosskey":1
            },
            "jp":"闇の神殿クリア",
            "types":{
                "shadow":1
            },
            "child":"yes",
            "name":"Beat the Shadow Temple"
        },
        {
            "subtypes":{
                "bosskey":1
            },
            "jp":"炎の結界の最後の部屋に到達\u001a",
            "types":{
                "fire":1,
                "ganon":1,
                "strength":1
            },
            "child":"no",
            "name":"Get to the end of Fire Trial"
        },
        {
            "jp":"金のグローブ",
            "types":{
                "strength":1,
                "deku":1,
                "ganon":1
            },
            "child":"yes",
            "name":"Golden Gauntlets"
        },
        {
            "jp":"魂の神殿のボムチュウ取得\u001a",
            "types":{
                "spirit":1
            },
            "child":"yes",
            "name":"Get Bombchu chest in Spirit Temple"
        },
        {
            "subtypes":{
                "hearts":1,
                "wallet":1
            },
            "jp":"ジャブジャブ様のお腹の黄金のスタルチュラ4匹",
            "types":{
                "jabu":1,
                "ice":1
            },
            "child":"yes",
            "name":"All 4 Skulltulas in Jabu-Jabu"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"妖精の弓",
            "types":{
                "quiver":1,
                "forest":1
            },
            "child":"no",
            "name":"Fairy Bow"
        },
        {
            "jp":"ダークリンク撃破",
            "types":{
                "water":1,
                "ice":1
            },
            "child":"no",
            "name":"Defeat Dark Link"
        },
        {
            "jp":"炎の矢",
            "types":{
                "fortress":1,
                "firearrow":1,
                "water":1,
                "quiver":1
            },
            "child":"no",
            "name":"Fire Arrow"
        }
    ],
    "13":[
        {
            "jp":"もだえ石",
            "types":{
                "wallet":1
            },
            "child":"yes",
            "name":"Stone of Agony"
        },
        {
            "jp":"ハート7つ",
            "types":{
                "hearts":1
            },
            "child":"yes",
            "name":"7 Hearts"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"ジャブジャブ様のお腹のマップとコンパス",
            "types":{
                "jabu":1
            },
            "child":"yes",
            "name":"Map & Compass in Jabu-Jabu"
        },
        {
            "subtypes":{
                "hearts":1,
                "child2":1
            },
            "jp":"ボムチュウボウリングの景品",
            "types":{
                "kd":1,
                "dc":1
            },
            "child":"yes",
            "name":"Win Bombchu Bowling Prize"
        },
        {
            "jp":"銀のグローブ",
            "types":{
                "strength":1,
                "spirit":1
            },
            "child":"yes",
            "name":"Silver Gauntlets"
        },
        {
            "jp":"ロングフック",
            "types":{
                "water":1,
                "ice":1
            },
            "child":"no",
            "name":"Longshot"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "wallet":1
            },
            "jp":"剣3種類と靴3種類",
            "types":{
                "swords":1,
                "ice":1,
                "boots":1
            },
            "child":"no",
            "name":"3 Swords & 3 Boots"
        }
    ],
    "14":[
        {
            "jp":"魔力2倍",
            "types":{
                "zl":1,
                "dmc":1
            },
            "child":"yes",
            "name":"Double Magic"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"歌8つ以上",
            "types":{
                "zl":1,
                "songs":1,
                "atrade":1
            },
            "child":"no",
            "name":"At least 8 songs"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"銅のグローブ",
            "types":{
                "strength":1,
                "ganon":1,
                "bulletbag":1,
                "atrade":1
            },
            "child":"no",
            "name":"Bronze Gauntlets"
        },
        {
            "jp":"キータンのお面",
            "types":{
                "zl":1
            },
            "child":"yes",
            "name":"Keaton Mask"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"服3種類と靴3種類\u001a",
            "types":{
                "fire":1,
                "ice":1,
                "tunics":1,
                "boots":1
            },
            "child":"no",
            "name":"3 Tunics & 3 Boots"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"森の神殿のボス部屋のカギ",
            "types":{
                "claimcheck":1,
                "quiver":1,
                "forest":1
            },
            "child":"no",
            "name":"Forest Temple Boss Key"
        }
    ],
    "15":[
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"ハイラル平原エリアの黄金ノスタルチュラ2匹",
            "types":{
                "zl":1,
                "water":1
            },
            "child":"yes",
            "name":"Both Hyrule Field area Skulltulas"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"森の神殿のマップとコンパス",
            "types":{
                "quiver":1,
                "forest":1
            },
            "child":"no",
            "name":"Map & Compass in Forest Temple"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"炎の神殿のマップとコンパス",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Map & Compass in Fire Temple"
        },
        {
            "subtypes":{
                "wallet":1,
                "child2":1
            },
            "jp":"ゲルドの谷エリアの黄金のスタルチュラ4匹",
            "types":{
                "fortress":1
            },
            "child":"no",
            "name":"All 4 Gerudo Valley area Skulltulas"
        },
        {
            "subtypes":{
                "child2":1,
                "wallet":1
            },
            "jp":"デスマウンテンエリアの黄金のスタルチュラ8匹",
            "types":{
                "dmc":1
            },
            "child":"no",
            "name":"All 8 Death Mountain area Skulltulas"
        },
        {
            "subtypes":{
                "child2":1,
                "wallet":1
            },
            "jp":"魔法のマメ9つ以上\u001a",
            "types":{
                "beans":1
            },
            "child":"yes",
            "name":"At least 9 Magic Beans"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"青のグローブ",
            "types":{
                "strength":1,
                "bulletbag":1,
                "spirit":1,
                "atrade":1
            },
            "child":"no",
            "name":"Blue Gauntlets"
        }
    ],
    "16":[
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"メガトンハンマー",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Megaton Hammer"
        },
        {
            "jp":"マップ6つ",
            "types":{
                "claimcheck":1,
                "mapcompass":1
            },
            "child":"yes",
            "name":"6 Maps"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"ゾーラの里エリアの黄金のスタルチュラ8匹",
            "types":{
                "jabu":1,
                "ice":1
            },
            "child":"no",
            "name":"All 8 Zora's Domain area Skulltulas"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"バリネード撃破",
            "types":{
                "jabu":1
            },
            "child":"yes",
            "name":"Defeat Barinade"
        },
        {
            "jp":"防御力2倍\u001a",
            "types":{
                "zl":1,
                "ganon":1
            },
            "child":"no",
            "name":"Double Defense"
        }
    ],
    "17":[
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"水の神殿の黄金のスタルチュラ3匹以上",
            "types":{
                "zl":1,
                "water":1,
                "ice":1
            },
            "child":"no",
            "name":"At least 3 Skulltulas in Water Temple"
        },
        {
            "subtypes":{
                "hearts":1,
                "songs":1
            },
            "jp":"カエルのハートのかけら(嵐の歌)",
            "types":{
                "pg":1,
                "child2":1,
                "forest":1
            },
            "child":"no",
            "name":"Frog's Heart Piece"
        },
        {
            "subtypes":{
                "hearts":1,
                "bosskey":1
            },
            "jp":"闇の神殿のボス部屋のカギ",
            "types":{
                "zl":1,
                "shadow":1
            },
            "child":"yes",
            "name":"Shadow Temple Boss Key"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"フレアダンサー2体撃破",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Defeat both Flare Dancers"
        },
        {
            "subtypes":{
                "hearts":1,
                "child2":1
            },
            "jp":"ジャブジャブ様のお腹クリア",
            "types":{
                "jabu":1
            },
            "child":"yes",
            "name":"Beat Jabu-Jabu's Belly"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"魂の神殿の黄金のスタルチュラ5匹",
            "types":{
                "spirit":1
            },
            "child":"yes",
            "name":"All 5 Skulltulas in Spirit Temple"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"剣3種類と盾3種類\u001a",
            "types":{
                "swords":1,
                "spirit":1,
                "shields":1
            },
            "child":"no",
            "name":"3 Swords & 3 Shields"
        },
        {
            "jp":"光の結界の最後の部屋に到達\u001a",
            "types":{
                "zl":1,
                "ganon":1,
                "strength":1
            },
            "child":"no",
            "name":"Get to the end of Light Trial"
        },
        {
            "jp":"ゲルドの修練場の未使用のカギ8つ",
            "types":{
                "fortress":1,
                "strength":1,
                "quiver":1
            },
            "child":"no",
            "name":"8 different unused keys in Gerudo Training Grounds"
        }
    ],
    "18":[
        {
            "jp":"コンパス6つ",
            "types":{
                "mapcompass":1
            },
            "child":"yes",
            "name":"6 Compasses"
        },
        {
            "jp":"フロルの風",
            "types":{
                "zl":1,
                "ice":1
            },
            "child":"yes",
            "name":"Farore's Wind"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "wallet":1,
                "bosskey":1
            },
            "jp":"炎の神殿の黄金のスタルチュラ5匹",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"All 5 Skulltulas in Fire Temple"
        },
        {
            "subtypes":{
                "pg":1,
                "mapcompass":1,
                "hearts":1,
                "bosskey":1
            },
            "jp":"ヴァルバジア撃破",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Defeat Volvagia"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"歌9つ以上",
            "types":{
                "zl":1,
                "songs":1,
                "atrade":1
            },
            "child":"no",
            "name":"At least 9 songs"
        }
    ],
    "19":[
        {
            "jp":"アイアンナック(ナボール)撃破",
            "types":{
                "spirit":1
            },
            "child":"no",
            "name":"Defeat Nabooru-Knuckle"
        },
        {
            "subtypes":{
                "child2":1,
                "songs":1
            },
            "jp":"サリアの歌",
            "types":{
                "zl":1,
                "saria":1
            },
            "child":"yes",
            "name":"Saria's Song"
        },
        {
            "jp":"ハート8つ",
            "types":{
                "hearts":1
            },
            "child":"yes",
            "name":"8 Hearts"
        },
        {
            "jp":"盾3種類と服3種類\u001a",
            "types":{
                "fire":1,
                "spirit":1,
                "tunics":1,
                "shields":1
            },
            "child":"no",
            "name":"3 Shields & 3 Tunics"
        },
        {
            "subtypes":{
                "pg":1,
                "mapcompass":1,
                "hearts":1,
                "bosskey":1
            },
            "jp":"炎の神殿クリア",
            "types":{
                "fire":1,
                "forest":1
            },
            "child":"no",
            "name":"Beat the Fire Temple"
        }
    ],
    "20":[
        {
            "jp":"光の矢",
            "types":{
                "zl":1,
                "lightarrow":1,
                "atrade":1
            },
            "child":"no",
            "name":"Light Arrows"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"メグ撃破(紫のポウ)",
            "types":{
                "quiver":1,
                "forest":1
            },
            "child":"no",
            "name":"Defeat Meg (purple Poe)"
        },
        {
            "subtypes":{
                "kd":1,
                "child2":1,
                "wallet":1
            },
            "jp":"幻影の砂漠・巨大邪神像エリアの黄金のスタルチュラ4匹",
            "types":{
                "spirit":1
            },
            "child":"no",
            "name":"All 4 Wasteland/ Colossus area Skulltulas"
        },
        {
            "jp":"ネールの愛",
            "types":{
                "zl":1,
                "spirit":1
            },
            "child":"yes",
            "name":"Nayru's Love"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"炎の神殿で９人のゴロンを全員救う",
            "types":{
                "fire":1
            },
            "child":"no",
            "name":"Free all 9 gorons in Fire Temple"
        }
    ],
    "21":[
        {
            "subtypes":{
                "child2":1
            },
            "jp":"ゴロンの腕輪",
            "types":{
                "zl":1,
                "strength":1,
                "saria":1
            },
            "child":"yes",
            "name":"Goron Bracelet"
        },
        {
            "subtypes":{
                "mapcompass":1,
                "child2":1,
                "wallet":1
            },
            "jp":"ハイリア湖畔エリアの黄金のスタルチュラ5匹",
            "types":{
                "water":1,
                "ice":1
            },
            "child":"no",
            "name":"All 5 Lake Hylia Skulltulas"
        },
        {
            "subtypes":{
                "child2":1
            },
            "jp":"ディンの炎\u001a",
            "types":{
                "zl":1
            },
            "child":"yes",
            "name":"Din's Fire"
        },
        {
            "jp":"魂の結界の最後の部屋に到達\u001a",
            "types":{
                "ganon":1,
                "spirit":1,
                "quiver":1
            },
            "child":"no",
            "name":"Get to the end of Spirit Trial"
        },
        {
            "subtypes":{
                "hearts":1,
                "wallet":1
            },
            "jp":"城下町エリアの黄金のスタルチュラ4匹",
            "types":{
                "pg":1,
                "child2":1,
                "forest":1
            },
            "child":"no",
            "name":"All 4 Market area Skulltulas"
        },
        {
            "jp":"こわそなお面",
            "types":{
                "zl":1,
                "fortress":1,
                "beans":1,
                "saria":1
            },
            "child":"yes",
            "name":"Spooky Mask"
        }
    ],
    "22":[
        {
            "jp":"マップ7つ",
            "types":{
                "claimcheck":1,
                "mapcompass":1
            },
            "child":"yes",
            "name":"7 Maps"
        },
        {
            "subtypes":{
                "bosskey":1
            },
            "jp":"魂の神殿のボス部屋のカギ",
            "types":{
                "zl":1,
                "lightarrow":1,
                "spirit":1
            },
            "child":"no",
            "name":"Spirit Temple Boss Key"
        },
        {
            "jp":"矢立て(50)",
            "types":{
                "fortress":1,
                "beans":1,
                "quiver":1
            },
            "child":"no",
            "name":"Quiver (50)"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"盾3種類と靴3種類\u001a",
            "types":{
                "ice":1,
                "spirit":1,
                "shields":1,
                "boots":1
            },
            "child":"yes",
            "name":"3 Shields & 3 Boots"
        }
    ],
    "23":[
        {
            "subtypes":{
                "hearts":1,
                "songs":1,
                "child2":1
            },
            "jp":"迷いの森のハートのかけら２つ",
            "types":{
                "zl":1
            },
            "child":"yes",
            "name":"Both heart pieces in Lost Woods"
        },
        {
            "subtypes":{
                "mapcompass":1
            },
            "jp":"魂の神殿のマップとコンパス",
            "types":{
                "zl":1,
                "spirit":1
            },
            "child":"yes",
            "name":"Map & Compass in Spirit Temple"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"ツインローバ撃破",
            "types":{
                "spirit":1
            },
            "child":"no",
            "name":"Defeat Twinrova"
        },
        {
            "subtypes":{
                "pg":1,
                "mapcompass":1,
                "bosskey":1
            },
            "jp":"水の結界の最後の部屋に到達\u001a",
            "types":{
                "fire":1,
                "ganon":1,
                "lightarrow":1
            },
            "child":"no",
            "name":"Get to the end of Water Trial"
        }
    ],
    "24":[
        {
            "subtypes":{
                "child2":1
            },
            "jp":"魔法のアイテム２つ",
            "types":{
                "zl":1,
                "spirit":1
            },
            "child":"yes",
            "name":"Two Fairy Spells"
        },
        {
            "subtypes":{
                "hearts":1
            },
            "jp":"魂の神殿クリア",
            "types":{
                "spirit":1
            },
            "child":"no",
            "name":"Beat the Spirit Temple"
        },
        {
            "subtypes":{
                "wallet":1,
                "bosskey":1
            },
            "jp":"闇の神殿の黄金のスタルチュラ5匹",
            "types":{
                "zl":1,
                "shadow":1
            },
            "child":"no",
            "name":"All 5 Skulltulas in Shadow Temple"
        },
        {
            "subtypes":{
                "pg":1,
                "mapcompass":1,
                "lightarrow":1,
                "bosskey":1
            },
            "jp":"闇の結界の最後の部屋に到達\u001a",
            "types":{
                "fire":1,
                "ganon":1
            },
            "child":"no",
            "name":"Get to the end of Shadow Trial"
        }
    ],
    "25":[
        {
            "jp":"ハート9つ",
            "types":{
                "hearts":1
            },
            "child":"yes",
            "name":"9 Hearts"
        },
        {
            "jp":"コンパス7つ",
            "types":{
                "mapcompass":1
            },
            "child":"no",
            "name":"7 Compasses"
        },
        {
            "jp":"水の神殿の黄金のスタルチュラ5匹",
            "types":{
                "zl":1,
                "water":1
            },
            "child":"no",
            "name":"All 5 Skulltulas in Water Temple"
        },
        {
            "subtypes":{
                "wallet":1
            },
            "jp":"緑のグローブ\u001a",
            "types":{
                "zl":1,
                "strength":1,
                "saria":1,
                "bulletbag":1,
                "atrade":1
            },
            "child":"no",
            "name":"Green Gauntlets"
        }
    ]
}
